import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Clock3, Loader2, PackageSearch, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useServerFn } from "@tanstack/react-start";
import { trackOrder } from "@/lib/commerce.functions";
import { rupiah, statusLabel } from "@/lib/store-data";

export const Route=createFileRoute("/cek-pesanan")({head:()=>({meta:[{title:"Cek Pesanan — CherryLuvv Market"},{name:"description",content:"Lacak status pesanan Pasar Setan menggunakan nomor pesanan dan identitasmu."},{property:"og:title",content:"Cek Pesanan CherryLuvv"},{property:"og:description",content:"Pantau proses item Pasar Setanmu."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:TrackPage});
type Tracked={order_number:string;status:string;payment_status:string;total_amount:number;roblox_username:string;payment_method:string;created_at:string};
function TrackPage(){const fn=useServerFn(trackOrder);const[orderNumber,setOrderNumber]=useState("");const[identity,setIdentity]=useState("");const[result,setResult]=useState<Tracked|null|undefined>(undefined);const[busy,setBusy]=useState(false);return <main className="mx-auto max-w-3xl px-4 py-16 sm:px-6"><div className="text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-secondary text-primary"><PackageSearch/></span><h1 className="mt-5 text-4xl font-black">Cek Pesanan</h1><p className="mt-2 text-muted-foreground">Masukkan nomor pesanan dan username Roblox atau nomor WhatsApp.</p></div><form className="mt-9 rounded-2xl border border-border bg-card p-6 shadow-soft" onSubmit={async e=>{e.preventDefault();setBusy(true);try{setResult(await fn({data:{orderNumber,identity}}) as Tracked|null)}finally{setBusy(false)}}}><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="order">Nomor Pesanan</Label><Input id="order" required maxLength={30} value={orderNumber} onChange={e=>setOrderNumber(e.target.value.toUpperCase())} className="mt-2 h-11 rounded-xl" placeholder="CLM-20260927-0001"/></div><div><Label htmlFor="identity">WhatsApp / Username Roblox</Label><Input id="identity" required maxLength={30} value={identity} onChange={e=>setIdentity(e.target.value)} className="mt-2 h-11 rounded-xl"/></div></div><Button disabled={busy} className="mt-5 h-11 w-full rounded-xl">{busy?<Loader2 className="animate-spin"/>:<Search/>}Cari Pesanan</Button></form>{result===null&&<div className="mt-6 rounded-2xl bg-muted p-8 text-center"><h2 className="font-black">Pesanan tidak ditemukan</h2><p className="mt-1 text-sm text-muted-foreground">Pastikan nomor pesanan dan identitas sama dengan data checkout.</p></div>}{result&&<div className="mt-6 rounded-2xl bg-footer p-6 text-footer-foreground shadow-float"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-footer-muted">Nomor pesanan</p><h2 className="text-2xl font-black">{result.order_number}</h2></div><span className="rounded-full bg-primary px-3 py-1 text-sm font-black text-primary-foreground">{statusLabel[result.status]}</span></div><div className="mt-6 grid gap-4 border-t border-footer-border pt-5 sm:grid-cols-2"><Info label="Akun Roblox" value={`@${result.roblox_username}`}/><Info label="Pembayaran" value={`${result.payment_method} · ${statusLabel[result.payment_status]}`}/><Info label="Total" value={rupiah(result.total_amount)}/><Info label="Dibuat" value={new Date(result.created_at).toLocaleDateString("id-ID")}/></div><p className="mt-6 flex items-center gap-2 text-sm text-footer-muted"><Clock3 className="size-4 text-primary"/>Status diperbarui oleh admin CherryLuvv.</p></div>}</main>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs text-footer-muted">{label}</p><p className="font-bold">{value}</p></div>}