import { useState } from "react";
import { createFileRoute, notFound, useNavigate } from "@tanstack/react-router";
import { CheckCircle2, Clock3, Minus, Plus, ShieldCheck, ShoppingBag, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getProduct } from "@/lib/commerce.functions";
import { imageFor, rupiah } from "@/lib/store-data";
import { useStore } from "@/components/store/store-context";
import { toast } from "sonner";

export const Route = createFileRoute("/produk/$slug")({
  loader: async ({params}) => { const product=await getProduct({data:{slug:params.slug}}); if(!product) throw notFound(); return product; },
  head: ({loaderData}) => ({meta:[{title:loaderData?`${loaderData.name} — CherryLuvv Market`:"Produk tidak ditemukan"},{name:"description",content:loaderData?.description??"Item Pasar Setan tidak ditemukan."},{property:"og:title",content:loaderData?.name??"CherryLuvv Market"},{property:"og:description",content:loaderData?.description??"Item Pasar Setan."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),
  notFoundComponent:()=> <div className="mx-auto max-w-xl px-4 py-32 text-center"><h1 className="text-3xl font-black">Item tidak ditemukan</h1><p className="mt-2 text-muted-foreground">Mungkin item ini sedang pindah lapak.</p></div>, component: ProductPage,
});
function ProductPage(){const product=Route.useLoaderData();const variants=[...(product.product_variants??[])].sort((a,b)=>a.sort_order-b.sort_order);const[selected,setSelected]=useState(variants[0]??null);const[qty,setQty]=useState(1);const{addItem}=useStore();const nav=useNavigate();const price=selected?.price??product.base_price;const add=()=>{addItem(product,selected,qty);toast.success("Item ditambahkan ke keranjang")};return <main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-2"><div className="overflow-hidden rounded-3xl bg-secondary shadow-soft"><img src={imageFor(product.image_key)} width={912} height={912} alt={product.name} className="aspect-square h-full w-full object-cover"/></div><div className="lg:py-5"><p className="font-bold text-primary">{product.categories?.name}</p><h1 className="mt-2 text-4xl font-black sm:text-5xl">{product.name}</h1><p className="mt-4 text-base leading-7 text-muted-foreground">{product.description}</p><div className="mt-6 flex items-center gap-4"><p className="text-3xl font-black">{rupiah(price)}</p><span className="rounded-full bg-success/10 px-3 py-1 text-sm font-bold text-success">Stok tersedia</span></div>{variants.length>0&&<div className="mt-7"><p className="mb-3 text-sm font-black">Pilih paket</p><div className="grid grid-cols-2 gap-2">{variants.map(v=><button key={v.id} onClick={()=>setSelected(v)} className={`rounded-xl border p-3 text-left transition ${selected?.id===v.id?"border-primary bg-accent text-accent-foreground":"border-border bg-card"}`}><b className="block text-sm">{v.name}</b><span className="text-xs">{rupiah(v.price)}</span></button>)}</div></div>}<div className="mt-7"><p className="mb-3 text-sm font-black">Jumlah</p><div className="flex w-fit items-center rounded-xl border border-border bg-card"><Button variant="ghost" size="icon" onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></Button><span className="w-12 text-center font-black">{qty}</span><Button variant="ghost" size="icon" onClick={()=>setQty(Math.min(99,qty+1))}><Plus/></Button></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><Button size="lg" className="h-12 rounded-xl" onClick={add}><ShoppingBag/>Tambah ke Keranjang</Button><Button size="lg" variant="outline" className="h-12 rounded-xl" onClick={()=>{add();nav({to:"/keranjang"})}}><Zap/>Beli Sekarang</Button></div><div className="mt-8 grid gap-3 rounded-2xl bg-muted p-5 text-sm"><p className="flex items-center gap-2 font-bold"><Clock3 className="size-4 text-primary"/>Estimasi proses {product.delivery_minutes}–30 menit</p><p className="flex items-center gap-2 font-bold"><ShieldCheck className="size-4 text-primary"/>Transaksi dan harga diverifikasi</p><p className="flex items-start gap-2 text-muted-foreground"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-success"/>{product.instructions}</p></div></div></div></main>}