/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CekPesananRouteImport } from './routes/cek-pesanan'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAkunRouteImport } from './routes/_authenticated/akun'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as ProdukSlugRouteImport } from './routes/produk.$slug'
import { Route as AuthenticatedBayarOrderIdRouteImport } from './routes/_authenticated/bayar.$orderId'
import { Route as AuthenticatedPesananOrderIdRouteImport } from './routes/_authenticated/pesanan.$orderId'
import { Route as ApiPublicWebhooksPakasirRouteImport } from './routes/api/public/webhooks/pakasir'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CekPesananRoute = CekPesananRouteImport.update({
  id: '/cek-pesanan',
  path: '/cek-pesanan',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAkunRoute = AuthenticatedAkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBayarOrderIdRoute =
  AuthenticatedBayarOrderIdRouteImport.update({
    id: '/bayar/$orderId',
    path: '/bayar/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPesananOrderIdRoute =
  AuthenticatedPesananOrderIdRouteImport.update({
    id: '/pesanan/$orderId',
    path: '/pesanan/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksPakasirRoute =
  ApiPublicWebhooksPakasirRouteImport.update({
    id: '/api/public/webhooks/pakasir',
    path: '/api/public/webhooks/pakasir',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cek-pesanan': typeof CekPesananRoute
  '/keranjang': typeof KeranjangRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/akun': typeof AuthenticatedAkunRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/bayar/$orderId': typeof AuthenticatedBayarOrderIdRoute
  '/pesanan/$orderId': typeof AuthenticatedPesananOrderIdRoute
  '/api/public/webhooks/pakasir': typeof ApiPublicWebhooksPakasirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cek-pesanan': typeof CekPesananRoute
  '/keranjang': typeof KeranjangRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/akun': typeof AuthenticatedAkunRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/bayar/$orderId': typeof AuthenticatedBayarOrderIdRoute
  '/pesanan/$orderId': typeof AuthenticatedPesananOrderIdRoute
  '/api/public/webhooks/pakasir': typeof ApiPublicWebhooksPakasirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cek-pesanan': typeof CekPesananRoute
  '/keranjang': typeof KeranjangRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/akun': typeof AuthenticatedAkunRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/_authenticated/bayar/$orderId': typeof AuthenticatedBayarOrderIdRoute
  '/_authenticated/pesanan/$orderId': typeof AuthenticatedPesananOrderIdRoute
  '/api/public/webhooks/pakasir': typeof ApiPublicWebhooksPakasirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cek-pesanan'
    | '/keranjang'
    | '/reset-password'
    | '/shop'
    | '/admin'
    | '/akun'
    | '/checkout'
    | '/produk/$slug'
    | '/bayar/$orderId'
    | '/pesanan/$orderId'
    | '/api/public/webhooks/pakasir'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cek-pesanan'
    | '/keranjang'
    | '/reset-password'
    | '/shop'
    | '/admin'
    | '/akun'
    | '/checkout'
    | '/produk/$slug'
    | '/bayar/$orderId'
    | '/pesanan/$orderId'
    | '/api/public/webhooks/pakasir'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cek-pesanan'
    | '/keranjang'
    | '/reset-password'
    | '/shop'
    | '/_authenticated/admin'
    | '/_authenticated/akun'
    | '/_authenticated/checkout'
    | '/produk/$slug'
    | '/_authenticated/bayar/$orderId'
    | '/_authenticated/pesanan/$orderId'
    | '/api/public/webhooks/pakasir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CekPesananRoute: typeof CekPesananRoute
  KeranjangRoute: typeof KeranjangRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  ApiPublicWebhooksPakasirRoute: typeof ApiPublicWebhooksPakasirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-pesanan': {
      id: '/cek-pesanan'
      path: '/cek-pesanan'
      fullPath: '/cek-pesanan'
      preLoaderRoute: typeof CekPesananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akun': {
      id: '/_authenticated/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AuthenticatedAkunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bayar/$orderId': {
      id: '/_authenticated/bayar/$orderId'
      path: '/bayar/$orderId'
      fullPath: '/bayar/$orderId'
      preLoaderRoute: typeof AuthenticatedBayarOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesanan/$orderId': {
      id: '/_authenticated/pesanan/$orderId'
      path: '/pesanan/$orderId'
      fullPath: '/pesanan/$orderId'
      preLoaderRoute: typeof AuthenticatedPesananOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/pakasir': {
      id: '/api/public/webhooks/pakasir'
      path: '/api/public/webhooks/pakasir'
      fullPath: '/api/public/webhooks/pakasir'
      preLoaderRoute: typeof ApiPublicWebhooksPakasirRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAkunRoute: typeof AuthenticatedAkunRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedBayarOrderIdRoute: typeof AuthenticatedBayarOrderIdRoute
  AuthenticatedPesananOrderIdRoute: typeof AuthenticatedPesananOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAkunRoute: AuthenticatedAkunRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedBayarOrderIdRoute: AuthenticatedBayarOrderIdRoute,
  AuthenticatedPesananOrderIdRoute: AuthenticatedPesananOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CekPesananRoute: CekPesananRoute,
  KeranjangRoute: KeranjangRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  ApiPublicWebhooksPakasirRoute: ApiPublicWebhooksPakasirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
